/* ==========================================================================
   Neuer Blick Verein e.V. - Shared Site Data
   Loaded by both the public website (index.html) and the admin studio (admin.html).
   Admin edits are stored as overrides in localStorage; these are the defaults.
   ========================================================================== */
const translations = {
  fa: {
    brandName: 'انجمن نگاه نو',
    brandSub: 'Neuer Blick Verein e.V.',
    navAbout: 'درباره ما',
    navActivities: 'فعالیت‌ها',
    navEvents: 'رویدادها',
    navStories: 'داستان‌های ما',
    navGallery: 'گالری',
    navMembership: 'عضویت',
    navContact: 'تماس با ما',
    loginButton: 'مدیریت',
    messageKicker: 'پیام انجمن',
    messageText: 'هر دیدار، یک پل تازه است. به جمع ما خوش آمدید.',
    messageTextTwo: 'فرهنگ ما، نقطه شروع آینده ماست.',
    messageTextThree: 'دیدار بعدی: شبی با دوستان و غذاهای سنتی افغان در مونستر',
    calloutEyebrow: 'ریشه‌هایی که با ما سفر می‌کنند',
    calloutText: 'از سرزمین کوه‌های سربه فلک کشیده تا قلب اروپا، فرهنگ، همدلی و داستان‌های ما پرامید ادامه دارد.',
    joinButton: 'به ما بپیوندید',
    discoverButton: 'بیشتر درباره ما',
    strip1Title: 'پایگاه فرهنگی در مونستر',
    strip1Sub: 'Münster, NRW Deutschland',
    strip2Title: 'مهمان‌نوازی و چای سنتی',
    strip2Sub: 'فضایی گرم و صمیمی برای همه',
    strip3Title: 'همبستگی و ادغام مثبت',
    strip3Sub: 'پل ارتباطی میان دوفرهنگ',
    eyebrow: 'از کابل تا مونستر، کنار هم',
    heroTitle: 'خانه‌ای برای فرهنگ، گفت‌وگو و آینده',
    heroCopy: 'انجمن نگاه نو (Neuer Blick Verein e.V.) بستری مستقل و پویا در آلمان است؛ جایی برای پاسداری از میراث کهن، توانمندسازی نسل جوان و ساختن فرصت‌های نوین تحصیلی، شغلی و اجتماعی.',
    stat1Desc: 'سال سابقه همراهی و فعالیت',
    stat2Desc: 'عضو، داوطلب و دوستدار انجمن',
    stat3Desc: 'کارگاه، سمینار و جشن فرهنگی',
    floatingStatText: 'داوطلبانه، مستقل و پویا',
    labelAbout: 'درباره انجمن',
    aboutTitle: 'ریشه‌های ما<br /><em>آینده‌ی ما</em> هستند.',
    aboutText: 'ما انجمنی غیرانتفاعی و مستقل در مونستر (Münster) هستیم؛ فضایی گرم برای حفظ فرهنگ غنی و اصیل، پشتیبانی از تازه‌واردین و پناهجویان، رشد جوانان و ساختن پل‌های مستحکم میان جامعه افغان و جامعه میزبان آلمان.',
    readMore: 'داستان ما را بخوانید',
    value1Title: 'هویت و فرهنگ',
    value1Text: 'پاسداری از زبان فارسی/دری، پشتو، شعر و ادب کهن و آیین‌های شادباستانی مانند نوروز و شب یلدا.',
    value2Title: 'آموزش و فرصت',
    value2Text: 'کارگاه‌های مهارت‌آموزی، راهنمای تحصیلی دانشگاهی، مشاوره اداری و دوره‌های زبان آلمانی.',
    value3Title: 'همبستگی و صلح',
    value3Text: 'ایجاد فضایی سرشار از احترام، امنیت و محبت برای همه اقوام، خانواده‌ها، جوانان و بانوان.',
    labelActivities: 'حضور و فعالیت‌های ما',
    activitiesTitle: 'چیزهایی که<br /><em>با هم می‌سازیم</em>',
    activitiesSub: 'برنامه‌های مداوم فرهنگی، آموزشی و گردهمایی‌های اجتماعی برای تمام سنین',
    activity1Title: 'فرهنگ، هنر و سنت‌ها',
    activity1Text: 'برگزاری شب‌های شعر و داستان‌خوانی، نمایشگاه صنایع دستی و قالیبافی سنتی و گردهمایی‌های جشن نوروز.',
    activity2Title: 'آموزش و یادگیری',
    activity2Text: 'کلاس‌های تقویتی برای دانش‌آموزان، آموزش مهارت‌های دیجیتال و جلسات تبادل زبان آلمانی-دری.',
    activity3Title: 'جوانان، بانوان و خانواده',
    activity3Text: 'فضایی گرم و امن برای گفت‌وگوی نسل جوان، کارگاه‌های توانمندسازی زنان، اردوهای تفریحی و چای‌نشینی‌های خانوادگی.',
    activity4Title: 'صلح و گفت‌وگوی بینافرهنگی',
    activity4Text: 'دیدارهای تبادل فرهنگی با نهادهای مدنی آلمانی، مبارزه با نژادپرستی و نمایش سیمای راستین و پویای جامعه افغان.',
    labelEvent: 'رویداد پیش رو',
    eventDate: 'شنبه، ۲۱ سپتامبر ۲۰۲۴ · مونستر، آلمان',
    eventTitle: 'یک میز،<br />هزار داستان.',
    eventText: 'شبی سرشار از عطر غذاهای ناب افغان، چای سبز با هل و شیرینی‌های خانگی، شعرخوانی و دیداری گرم برای خانواده‌ها و علاقه‌مندان به فرهنگ افغانستان در مونستر.',
    eventButton: 'ثبت‌نام در رویداد',
    eventLocationBtn: 'محل برگزاری',
    labelGallery: 'گالری تصویری انجمن',
    galleryTitle: 'لحظه‌هایی که<br /><em>می‌مانند.</em>',
    galleryHint: 'روی هر تصویر کلیک کنید تا در اندازه بزرگ مشاهده نمایید.',
    quote: 'وقتی کنار هم می‌ایستیم، خانه دیگر فقط یک نقطه روی نقشه نیست؛ حسی است که با قلب‌هایمان، فرهنگ‌مان و همدلی‌مان در غربت می‌سازیم.',
    quoteBy: '— یکی از اعضای انجمن نگاه نو در مونستر',
    labelTogether: 'با ما همراه شوید',
    membershipTitle: 'جای شما<br /><em>اینجاست.</em>',
    membershipText: 'عضو رسمی شوید، به عنوان داوطلب تجربیات خود را به اشتراک بگذارید یا فقط برای یک پیاله چای سبز با هل و گفت‌وگویی دوستانه به جمع ما بیایید. هر حضوری، یک دلگرمی تازه است.',
    membershipButton: 'تکمیل فرم عضویت',
    labelContact: 'در تماس باشیم',
    contactTitle: 'سلام کنید،<br /><em>ما اینجاییم.</em>',
    contactText: 'برای پیشنهاد همکاری، عضویت، داوطلبی یا هر پرسشی درباره برنامه‌های انجمن، با ما در ارتباط باشید.',
    contactMessageBtn: 'ارسال پیام سریع',
    addressLabel: 'آدرس دفتر مرکزی',
    phoneLabel: 'تلفن تماس',
    emailLabel: 'پست الکترونیکی',
    footerText: 'فرهنگ. همبستگی. امید به فردا.',
    footerContact: 'تماس با ما',
    footerLegal: 'اطلاعات حقوقی (Impressum)',
    footerPrivacy: 'حفاظت داده‌ها (Datenschutz)',
    socialLabel: 'شبکه‌های اجتماعی ما:',
    formNameLabel: 'نام و نام خانوادگی *',
    formEmailLabel: 'پست الکترونیکی (ایمیل) *',
    formPhoneLabel: 'شماره تماس / واتساپ',
    formInterestLabel: 'نوع درخواست',
    formNotesLabel: 'پیام یا یادداشت شما (اختیاری)',
    formSubmitBtn: 'ارسال درخواست',
    munsterCity: 'مونستر',
    kabulCity: 'کابل',
    messageTextFour: 'همراهی و مشاوره رایگان برای کار و تحصیل در آلمان',
    navOpportunities: 'کار و تحصیل در آلمان',
    labelOpportunities: 'آینده و رشد در آلمان',
    opportunitiesTitle: 'فرصت‌های شغلی،<br /><em>تحصیل و بورسیه‌ها</em>',
    opportunitiesSub: 'راهنمای جامع و حمایت انجمن نگاه نو برای ورود موفق به بازار کار، دانشگاه‌ها و برنامه‌های بورسیه در آلمان',
    jobTag: 'اشتغال و تخصص',
    jobCardTitle: 'فرصت‌های شغلی و ورود به بازار کار',
    jobCardDesc: 'مسیرهای کاربردی برای اشتغال رسمی، ارزیابی مدارک تحصیلی و فنی، و دوره‌های کارآموزی دوگانه در سراسر آلمان.',
    jobP1Title: 'معادل‌سازی مدارک (Anerkennung)',
    jobP1Desc: 'راهنمایی گام‌به‌گام برای تایید مدارک مهندسی، پزشکی، حسابداری و فنی در ادارات آلمان.',
    jobP2Title: 'دوره‌های کارآموزی دوگانه (Ausbildung)',
    jobP2Desc: 'کسب تخصص همراه با دریافت حقوق ماهیانه برای بیش از ۳۵۰ رشته فنی، بازرگانی و خدماتی.',
    jobP3Title: 'رزومه‌نویسی حرفه‌ای (Bewerbung)',
    jobP3Desc: 'تدوین رزومه آلمانی (Lebenslauf) و انگیزه‌نامه استاندارد متناسب با کارفرمایان مونستر و NRW.',
    jobP4Title: 'کاریابی و شبکه‌سازی شغلی',
    jobP4Desc: 'معرفی پورتال‌های معتبر دولتی و خصوصی (Arbeitsagentur, StepStone) و ارتباط با کارآفرینان افغان.',
    jobActionBtn: 'مشاوره شغلی رایگان',
    studyTag: 'دانشگاه و بورسیه',
    studyCardTitle: 'تحصیل در آلمان و بورسیه‌های تحصیلی',
    studyCardDesc: 'راهنمای پذیرش در دانشگاه‌های معتبر آلمان، دوره‌های رایگان کارشناسی و ارشد، و دریافت کمک‌هزینه‌های تحصیلی.',
    studyP1Title: 'پذیرش دانشگاهی و کالج (Uni-Assist)',
    studyP1Desc: 'نحوه اقدام برای پذیرش در دانشگاه‌های دولتی، گذراندن Studienkolleg و انتخاب رشته‌های آینده‌دار.',
    studyP2Title: 'بورسیه‌های معتبر (DAAD & Foundations)',
    studyP2Desc: 'آشنایی با بورسیه‌های DAAD، بنیادهای بوش، بوی و ابرت و کمک‌هزینه‌های دولتی BAföG.',
    studyP3Title: 'آزمون‌های زبان آلمانی (TestDaF & DSH)',
    studyP3Desc: 'منابع و کارگاه‌های تقویت زبان برای کسب سطح B2 و C1 جهت ورود به دانشگاه‌های آلمان.',
    studyP4Title: 'منتورشیپ و راهنمایی دانشجویی',
    studyP4Desc: 'همراهی مستقیم با دانشجویان و دانش‌آموختگان افغان در دانشگاه مونستر (WWU) و سایر دانشگاه‌ها.',
    studyActionBtn: 'راهنمایی تحصیلی و بورسیه',
    moreInfo: 'اطلاعات بیشتر',
    frameCaption: 'با هم قوی‌تر هستیم',
    tagFood: '🍲 غذای سنتی',
    tagTea: '🫖 چای و شیرینی',
    tagTalk: '🗣 گفت‌وگو',
    tagFree: '🎟 ورود آزاد',
    cdLabel: 'تا آغاز رویداد',
    cdDays: 'روز',
    cdHours: 'ساعت',
    cdMinutes: 'دقیقه',
    cdSeconds: 'ثانیه',
    cdSoon: 'تاریخ رویداد بعدی به‌زودی اعلام می‌شود.',
    addCalendar: 'افزودن به تقویم',
    shareEvent: 'اشتراک‌گذاری',
    benefit1: 'شرکت در کارگاه‌ها و کلاس‌های اختصاصی',
    benefit2: 'تخفیف و اولویت در جشن‌ها و رویدادهای سالانه',
    benefit3: 'شبکه حمایت تحصیلی، کاری و حقوقی در آلمان',
    artTitle: 'عضویت در نگاه نو',
    artText: 'یک خانواده بزرگ، حامی فرهنگ و آینده افغان در مونستر و آلمان',
    labelFaq: 'پرسش‌های پرتکرار',
    faqTitle: 'پرسشی دارید؟<br /><em>پاسخ اینجاست.</em>',
    faqSub: 'پاسخ کوتاه به رایج‌ترین پرسش‌ها درباره عضویت، مشاوره و برنامه‌های انجمن.',
    faqAsk: 'پرسش دیگری دارید؟',
    faq1Q: 'چه کسانی می‌توانند عضو انجمن شوند؟',
    faq1A: 'همه کسانی که به فرهنگ افغانستان و همبستگی اجتماعی علاقه دارند، از هر قوم، سن و ملیتی، می‌توانند عضو شوند. کافی است فرم عضویت را تکمیل کنید.',
    faq2Q: 'آیا مشاوره کار و تحصیل رایگان است؟',
    faq2A: 'بله. همراهی انجمن در زمینه کار، آوسبیلدونگ، تحصیل و بورسیه به‌صورت داوطلبانه و رایگان ارائه می‌شود.',
    faq3Q: 'برنامه‌ها به چه زبان‌هایی برگزار می‌شوند؟',
    faq3A: 'برنامه‌ها بیشتر به دری/فارسی، پشتو و آلمانی برگزار می‌شوند و در صورت نیاز به انگلیسی نیز کمک می‌کنیم.',
    faq4Q: 'چگونه می‌توانم داوطلب شوم؟',
    faq4A: 'فرم تماس را باز کنید و گزینه «همکاری داوطلبانه» را انتخاب کنید. تیم ما برای آشنایی و هماهنگی با شما تماس می‌گیرد.',
    faq5Q: 'دفتر انجمن کجاست؟',
    faq5A: 'دفتر ما در Strinfurter Straße 70، 48149 Münster قرار دارد. برای دیدار حضوری، لطفاً پیش از آمدن با ما هماهنگ کنید.',
    actCall: 'تماس تلفنی',
    actWhatsapp: 'واتساپ',
    actEmail: 'ایمیل',
    actRoute: 'مسیریابی',
    copied: 'کپی شد!',
    linkCopied: 'لینک رویداد کپی شد.',
    footerArtCaption: 'از کابل تا مونستر؛ پلی از فرهنگ، دوستی و امید',
    footerAbout: 'انجمنی مستقل و غیرانتفاعی در مونستر برای فرهنگ، آموزش و همبستگی جامعه افغان.',
    footerExplore: 'کاوش',
    footerPrograms: 'برنامه‌ها',
    newsletterTitle: 'خبرنامه انجمن',
    newsletterText: 'از رویدادها و فرصت‌های تازه زودتر از همه باخبر شوید.',
    newsletterDone: 'ایمیل شما در خبرنامه ثبت شد. سپاسگزاریم!',
    footerMade: 'ساخته‌شده با ♥ در مونستر',
    devLabel: 'طراحی و توسعه:',
    devName: 'شعيب عبيدی',
    messageKickerTwo: 'Kabul ↔ Münster',
    frameCity: 'Münster, Deutschland',
    floatingStatValue: '100%',
    stampCity: 'MÜNSTER',
    stampYear: '2026',
    artBadge: 'Vereinsmitglied',
    artFooter: 'Münster e.V.',
    footerCopyright: 'Neuer Blick Verein e.V. · Alle Rechte vorbehalten.',
    modalBadge: 'Neuer Blick e.V.',
    loaderText: 'انجمن نگاه نو · مونستر',
    scrollHint: 'SCROLL',
    modalMembershipTitle: 'فرم عضویت در انجمن نگاه نو',
    modalMembershipSub: 'به جمع گرم ما در مونستر بپیوندید. مشتاق دیدار شما هستیم.',
    modalEventTitle: 'ثبت‌نام در رویداد فرهنگی: یک میز، هزار داستان',
    modalEventSub: 'جای خود را برای شبی به‌یادماندنی با غذاهای اصیل و دیدار دوستان رزرو کنید.',
    modalJobTitle: 'مشاوره شغلی و کار در آلمان',
    modalJobSub: 'راهنمایی رایگان معادل‌سازی مدارک، آوسبیلدونگ و اشتغال در آلمان.',
    modalStudyTitle: 'مشاوره پذیرش دانشگاهی و بورسیه تحصیلی',
    modalStudySub: 'راهنمای پذیرش دانشگاه‌ها، آزمون‌های زبان و بورسیه‌های تحصیلی.',
    modalGeneralTitle: 'ارسال پیام به انجمن',
    modalGeneralSub: 'پرسش، پیشنهاد یا پیام خود را برای ما بنویسید.',
    thanksMsg: 'سپاسگزاریم {name} عزیز! پیام شما با موفقیت ثبت شد.',
    friendWord: 'دوست گرامی',
    sendError: 'ارسال ناموفق بود. لطفاً دوباره تلاش کنید یا به ما ایمیل بزنید.',
    sending: 'در حال ارسال...',
    optMembership: 'درخواست عضویت در انجمن',
    optEvent: 'ثبت‌نام در رویداد فرهنگی',
    optJob: 'مشاوره شغلی و کاریابی در آلمان',
    optStudy: 'راهنمایی تحصیلی، دانشگاه و بورسیه',
    optVolunteer: 'همکاری داوطلبانه و آموزش',
    optGeneral: 'پرسش عمومی یا همکاری',
    formNamePh: 'مثال: احمد رحیمی',
    formNotesPh: 'توضیحات یا پیام خود را اینجا بنویسید...'
  },
  ps: {
    brandName: 'د نوي نظر ټولنه',
    brandSub: 'Neuer Blick Verein e.V.',
    navAbout: 'زموږ په اړه',
    navActivities: 'فعالیتونه',
    navEvents: 'پېښې',
    navStories: 'زموږ کیسې',
    navGallery: 'ګالري',
    navMembership: 'غړیتوب',
    navContact: 'اړیکه',
    loginButton: 'مدیریت',
    messageKicker: 'د ټولنې پیغام',
    messageText: 'هره لیدنه یو نوی پل دی. زموږ ټولنې ته ښه راغلاست.',
    messageTextTwo: 'زموږ کلتور د راتلونکي پیل ټکی دی.',
    messageTextThree: 'راتلونکې لیدنه: په مونستر کې د ملګرو او دودیزو افغاني خوړو یوه شپه',
    calloutEyebrow: 'هغه ریښې چې له موږ سره سفر کوي',
    calloutText: 'د لوړو غرونو له خاورې تر اروپا زړه پورې، زموږ کلتور، خواخوږي او کیسې په هیله‌مندۍ دوام لري.',
    joinButton: 'موږ سره یوځای شئ',
    discoverButton: 'زموږ په اړه نور',
    strip1Title: 'په مونستر کې کلتوري مرکز',
    strip1Sub: 'Münster, NRW Deutschland',
    strip2Title: 'مېلمه‌پالنه او دودیزه چای',
    strip2Sub: 'د ټولو لپاره تود او خوږ ځای',
    strip3Title: 'یووالی او مثبت ادغام',
    strip3Sub: 'د دوو کلتورونو ترمنځ پل',
    eyebrow: 'له کابله تر مونستره، یوځای',
    heroTitle: 'د کلتور، خبرو اترو او راتلونکي لپاره یو کور',
    heroCopy: 'د نوي نظر ټولنه (Neuer Blick Verein e.V.) په آلمان کې یوه خپلواکه او فعاله ټولنه ده؛ د لرغوني میراث د ساتنې، د ځوان نسل د پیاوړتیا او د زده‌کړې، کار او ټولنیزو نویو فرصتونو د جوړولو ځای.',
    stat1Desc: 'کاله ملګرتیا او فعالیت',
    stat2Desc: 'غړي، رضاکاران او مینه‌وال',
    stat3Desc: 'ورکشاپونه، سیمینارونه او کلتوري جشنونه',
    floatingStatText: 'رضاکارانه، خپلواکه او فعاله',
    labelAbout: 'د ټولنې په اړه',
    aboutTitle: 'زموږ ریښې<br /><em>زموږ راتلونکی</em> دي.',
    aboutText: 'موږ په مونستر (Münster) کې یوه غیرانتفاعي او خپلواکه ټولنه یو؛ د بډای او اصیل کلتور د ساتنې، د نویو راغلو او کډوالو د ملاتړ، د ځوانانو د ودې او د افغان ټولنې او آلماني کوربه ټولنې ترمنځ د ټینګو پلونو د جوړولو لپاره یو تود ځای.',
    readMore: 'زموږ کیسه ولولئ',
    value1Title: 'هویت او کلتور',
    value1Text: 'د پښتو او دري ژبو، شعر او لرغوني ادب او د نوروز په څېر د خوښیو د دودونو ساتنه.',
    value2Title: 'زده‌کړه او فرصت',
    value2Text: 'د مهارتونو ورکشاپونه، پوهنتوني لارښوونه، اداري مشورې او د آلماني ژبې کورسونه.',
    value3Title: 'یووالی او سوله',
    value3Text: 'د ټولو قومونو، کورنیو، ځوانانو او مېرمنو لپاره د درناوي، امنیت او مینې ډک ځای.',
    labelActivities: 'زموږ شتون او فعالیتونه',
    activitiesTitle: 'هغه څه چې<br /><em>یوځای یې جوړوو</em>',
    activitiesSub: 'د ټولو عمرونو لپاره دوامداره کلتوري، ښوونیز او ټولنیز پروګرامونه',
    activity1Title: 'کلتور، هنر او دودونه',
    activity1Text: 'د شعر او کیسه‌ویلو شپې، د لاسي صنایعو او دودیزو قالینو نندارتونونه او د نوروز جشنونه.',
    activity2Title: 'زده‌کړه او ښوونه',
    activity2Text: 'زده‌کوونکو ته تقویتي ټولګي، ډیجیټل مهارتونه او د آلماني-پښتو ژبو تبادلې غونډې.',
    activity3Title: 'ځوانان، مېرمنې او کورنۍ',
    activity3Text: 'د ځوان نسل د خبرو اترو لپاره تود او خوندي ځای، د مېرمنو د پیاوړتیا ورکشاپونه، تفریحي سفرونه او کورنۍ چای‌څښنې.',
    activity4Title: 'سوله او بین‌الکلتوري خبرې اترې',
    activity4Text: 'له آلماني مدني بنسټونو سره کلتوري تبادلې، له توکمپالنې سره مبارزه او د افغان ټولنې د ریښتیني انځور ښودل.',
    labelEvent: 'راتلونکې پېښه',
    eventDate: 'شنبه، ۲۱ سپتامبر ۲۰۲۴ · مونستر، آلمان',
    eventTitle: 'یو دسترخوان،<br />زر کیسې.',
    eventText: 'د خوندورو افغاني خوړو، د هېل لرونکې شنې چای او کورنیو خوږو، شعرلوستلو او تودې لیدنې یوه شپه د کورنیو او د افغان کلتور د مینه‌والو لپاره په مونستر کې.',
    eventButton: 'په پېښه کې نوم لیکنه',
    eventLocationBtn: 'د پېښې ځای',
    labelGallery: 'د ټولنې انځوري ګالري',
    galleryTitle: 'هغه شېبې چې<br /><em>پاتې کېږي.</em>',
    galleryHint: 'په هر انځور کلیک وکړئ چې په لوی اندازه یې وګورئ.',
    quote: 'کله چې یوځای ودرېږو، کور نور یوازې په نقشه کې یو ټکی نه دی؛ یو احساس دی چې په پردیسۍ کې یې د خپلو زړونو، کلتور او خواخوږۍ سره جوړوو.',
    quoteBy: '— په مونستر کې د نوي نظر ټولنې یو غړی',
    labelTogether: 'له موږ سره ملګري شئ',
    membershipTitle: 'ستاسو ځای<br /><em>همدلته دی.</em>',
    membershipText: 'رسمي غړی شئ، د رضاکار په توګه خپلې تجربې شریکې کړئ یا یوازې د هېل لرونکې شنې چای یوې پیالې او دوستانه خبرو لپاره موږ ته راشئ. هر راتګ یوه نوې زړه‌ورتیا ده.',
    membershipButton: 'د غړیتوب فورمه ډکه کړئ',
    labelContact: 'په اړیکه کې پاتې شو',
    contactTitle: 'سلام ووایاست،<br /><em>موږ دلته یو.</em>',
    contactText: 'د همکارۍ وړاندیز، غړیتوب، رضاکارۍ یا د ټولنې د پروګرامونو په اړه د هرې پوښتنې لپاره له موږ سره اړیکه ونیسئ.',
    contactMessageBtn: 'چټک پیغام ولېږئ',
    addressLabel: 'د مرکزي دفتر پته',
    phoneLabel: 'د اړیکې شمېره',
    emailLabel: 'برېښنالیک',
    footerText: 'کلتور. یووالی. د سبا هیله.',
    footerContact: 'اړیکه',
    footerLegal: 'حقوقي معلومات (Impressum)',
    footerPrivacy: 'د معلوماتو ساتنه (Datenschutz)',
    socialLabel: 'زموږ ټولنیزې شبکې:',
    formNameLabel: 'نوم او تخلص *',
    formEmailLabel: 'برېښنالیک (ایمیل) *',
    formPhoneLabel: 'د تلیفون / واټساپ شمېره',
    formInterestLabel: 'د غوښتنې ډول',
    formNotesLabel: 'ستاسو پیغام یا یادښت (اختیاري)',
    formSubmitBtn: 'غوښتنه ولېږئ',
    munsterCity: 'مونستر',
    kabulCity: 'کابل',
    messageTextFour: 'په آلمان کې د کار او زده‌کړې لپاره وړیا ملګرتیا او مشوره',
    navOpportunities: 'په آلمان کې کار او زده‌کړه',
    labelOpportunities: 'په آلمان کې راتلونکی او وده',
    opportunitiesTitle: 'د کار فرصتونه،<br /><em>زده‌کړه او بورسونه</em>',
    opportunitiesSub: 'په آلمان کې د کار بازار، پوهنتونونو او بورسونو ته د بریالي ننوتو لپاره د نوي نظر ټولنې بشپړه لارښوونه او ملاتړ',
    jobTag: 'کار او مسلک',
    jobCardTitle: 'د کار فرصتونه او کار بازار ته ننوتل',
    jobCardDesc: 'رسمي کار ته عملي لارې، د تحصیلي او مسلکي اسنادو ارزونه، او په ټول آلمان کې دوه‌اړخیزې مسلکي زده‌کړې.',
    jobP1Title: 'د اسنادو معادل کول (Anerkennung)',
    jobP1Desc: 'په آلماني ادارو کې د انجنیرۍ، طب، محاسبې او تخنیکي اسنادو د تایید لپاره ګام په ګام لارښوونه.',
    jobP2Title: 'دوه‌اړخیزه مسلکي زده‌کړه (Ausbildung)',
    jobP2Desc: 'له ۳۵۰ څخه زیاتو تخنیکي، سوداګریزو او خدماتي برخو کې د میاشتني معاش سره مسلک زده کول.',
    jobP3Title: 'مسلکي سوانح لیکل (Bewerbung)',
    jobP3Desc: 'د مونستر او NRW کارګمارونکو ته د آلماني معیاري سوانحو (Lebenslauf) او انګیزې لیک چمتو کول.',
    jobP4Title: 'کار موندل او مسلکي شبکې',
    jobP4Desc: 'د باوري دولتي او خصوصي پورټالونو (Arbeitsagentur, StepStone) معرفي او له افغان کارګمارونکو سره اړیکه.',
    jobActionBtn: 'وړیا مسلکي مشوره',
    studyTag: 'پوهنتون او بورس',
    studyCardTitle: 'په آلمان کې زده‌کړه او تحصیلي بورسونه',
    studyCardDesc: 'د آلمان معتبرو پوهنتونونو ته د داخلې لارښود، وړیا لیسانس او ماسټري پروګرامونه، او د زده‌کړې مرستې.',
    studyP1Title: 'پوهنتوني داخله (Uni-Assist)',
    studyP1Desc: 'دولتي پوهنتونونو ته د داخلې طریقه، Studienkolleg تېرول او د راتلونکي لرونکو رشتو ټاکل.',
    studyP2Title: 'معتبر بورسونه (DAAD & Foundations)',
    studyP2Desc: 'د DAAD بورسونو، د بوش، بول او ایبرټ بنسټونو او د BAföG دولتي مرستو پېژندنه.',
    studyP3Title: 'د آلماني ژبې ازموینې (TestDaF & DSH)',
    studyP3Desc: 'د آلمان پوهنتونونو ته د ننوتو لپاره د B2 او C1 کچې ترلاسه کولو سرچینې او ورکشاپونه.',
    studyP4Title: 'د محصلینو لارښوونه (Mentoring)',
    studyP4Desc: 'د مونستر پوهنتون (WWU) او نورو پوهنتونونو له افغان محصلینو او فارغانو سره مستقیمه ملګرتیا.',
    studyActionBtn: 'تحصیلي او د بورس لارښوونه',
    moreInfo: 'نور معلومات',
    frameCaption: 'یوځای پیاوړي یو',
    tagFood: '🍲 دودیز خواړه',
    tagTea: '🫖 چای او خواږه',
    tagTalk: '🗣 خبرې اترې',
    tagFree: '🎟 وړیا ننوتل',
    cdLabel: 'د پېښې تر پیله',
    cdDays: 'ورځې',
    cdHours: 'ساعته',
    cdMinutes: 'دقیقې',
    cdSeconds: 'ثانیې',
    cdSoon: 'د راتلونکې پېښې نېټه به ژر اعلان شي.',
    addCalendar: 'جنتري ته ورزیاتول',
    shareEvent: 'شریکول',
    benefit1: 'په ځانګړو ورکشاپونو او ټولګیو کې ګډون',
    benefit2: 'په کلنیو جشنونو او پېښو کې لومړیتوب او تخفیف',
    benefit3: 'په آلمان کې د زده‌کړې، کار او حقوقي ملاتړ شبکه',
    artTitle: 'په نوي نظر کې غړیتوب',
    artText: 'یوه لویه کورنۍ چې په مونستر او آلمان کې د افغان کلتور او راتلونکي ملاتړ کوي',
    labelFaq: 'تکراري پوښتنې',
    faqTitle: 'پوښتنه لرئ؟<br /><em>ځواب دلته دی.</em>',
    faqSub: 'د غړیتوب، مشورې او د ټولنې د پروګرامونو په اړه عامو پوښتنو ته لنډ ځوابونه.',
    faqAsk: 'بله پوښتنه لرئ؟',
    faq1Q: 'څوک د ټولنې غړي کېدای شي؟',
    faq1A: 'هر هغه څوک چې د افغانستان له کلتور او ټولنیز یووالي سره مینه لري، له هر قوم، عمر او تابعیت څخه، غړی کېدای شي. یوازې د غړیتوب فورمه ډکه کړئ.',
    faq2Q: 'ایا د کار او زده‌کړې مشوره وړیا ده؟',
    faq2A: 'هو. د کار، آوسبیلډونګ، زده‌کړې او بورس په برخه کې د ټولنې ملګرتیا رضاکارانه او وړیا ده.',
    faq3Q: 'پروګرامونه په کومو ژبو جوړېږي؟',
    faq3A: 'پروګرامونه زیاتره په پښتو، دري/فارسي او آلماني ژبو جوړېږي او د اړتیا په صورت کې په انګلیسي هم مرسته کوو.',
    faq4Q: 'څنګه رضاکار کېدای شم؟',
    faq4A: 'د اړیکې فورمه پرانیزئ او «رضاکارانه همکاري» وټاکئ. زموږ ټیم به د پېژندګلوۍ او همغږۍ لپاره درسره اړیکه ونیسي.',
    faq5Q: 'د ټولنې دفتر چېرته دی؟',
    faq5A: 'زموږ دفتر په Strinfurter Straße 70، 48149 Münster کې دی. د حضوري لیدنې لپاره مهرباني وکړئ مخکې له موږ سره وخت وټاکئ.',
    actCall: 'تلیفون',
    actWhatsapp: 'واټساپ',
    actEmail: 'ایمیل',
    actRoute: 'لارښود',
    copied: 'کاپي شو!',
    linkCopied: 'د پېښې لینک کاپي شو.',
    footerArtCaption: 'له کابله تر مونستره؛ د کلتور، دوستۍ او هیلې پل',
    footerAbout: 'په مونستر کې د افغان ټولنې د کلتور، زده‌کړې او یووالي لپاره یوه خپلواکه او غیرانتفاعي ټولنه.',
    footerExplore: 'وپلټئ',
    footerPrograms: 'پروګرامونه',
    newsletterTitle: 'د ټولنې خبرپاڼه',
    newsletterText: 'د پېښو او نویو فرصتونو څخه تر ټولو مخکې خبر شئ.',
    newsletterDone: 'ستاسو ایمیل په خبرپاڼه کې ثبت شو. مننه!',
    footerMade: 'په مونستر کې په ♥ جوړ شوی',
    devLabel: 'ډیزاین او پراختیا:',
    devName: 'شعیب عبیدي',
    messageKickerTwo: 'Kabul ↔ Münster',
    frameCity: 'Münster, Deutschland',
    floatingStatValue: '100%',
    stampCity: 'MÜNSTER',
    stampYear: '2026',
    artBadge: 'Vereinsmitglied',
    artFooter: 'Münster e.V.',
    footerCopyright: 'Neuer Blick Verein e.V. · Alle Rechte vorbehalten.',
    modalBadge: 'Neuer Blick e.V.',
    loaderText: 'د نوي نظر ټولنه · مونستر',
    scrollHint: 'SCROLL',
    modalMembershipTitle: 'د نوي نظر ټولنې د غړیتوب فورمه',
    modalMembershipSub: 'په مونستر کې زموږ تودې ټولنې سره یوځای شئ. ستاسو لیدو ته سترګې په لار یو.',
    modalEventTitle: 'په کلتوري پېښه کې نوم لیکنه: یو دسترخوان، زر کیسې',
    modalEventSub: 'د اصیلو خوړو او ملګرو سره د یوې نه هېرېدونکې شپې لپاره خپل ځای خوندي کړئ.',
    modalJobTitle: 'په آلمان کې مسلکي مشوره او کار',
    modalJobSub: 'د اسنادو معادل کولو، آوسبیلډونګ او په آلمان کې د کار لپاره وړیا لارښوونه.',
    modalStudyTitle: 'د پوهنتوني داخلې او تحصیلي بورس مشوره',
    modalStudySub: 'پوهنتونونو ته د داخلې، ژبني ازموینو او تحصیلي بورسونو لارښود.',
    modalGeneralTitle: 'ټولنې ته پیغام ولېږئ',
    modalGeneralSub: 'خپله پوښتنه، وړاندیز یا پیغام موږ ته ولیکئ.',
    thanksMsg: 'ګرانه {name}، مننه! ستاسو پیغام په بریالیتوب سره ثبت شو.',
    friendWord: 'ګران ملګری',
    sendError: 'لېږل ناکام شول. مهرباني وکړئ بیا هڅه وکړئ یا موږ ته ایمیل ولیکئ.',
    sending: 'د لېږلو په حال کې...',
    optMembership: 'په ټولنه کې د غړیتوب غوښتنه',
    optEvent: 'په کلتوري پېښه کې نوم لیکنه',
    optJob: 'په آلمان کې مسلکي مشوره او کار موندنه',
    optStudy: 'تحصیلي لارښوونه، پوهنتون او بورس',
    optVolunteer: 'رضاکارانه همکاري او تدریس',
    optGeneral: 'عمومي پوښتنه یا همکاري',
    formNamePh: 'بېلګه: احمد رحیمي',
    formNotesPh: 'خپل توضیحات یا پیغام دلته ولیکئ...'
  },
  de: {
    brandName: 'Neuer Blick Verein',
    brandSub: 'انجمن نگاه نو در مونستر',
    navAbout: 'Über uns',
    navActivities: 'Aktivitäten',
    navEvents: 'Veranstaltungen',
    navStories: 'Geschichten',
    navGallery: 'Galerie',
    navMembership: 'Mitgliedschaft',
    navContact: 'Kontakt',
    loginButton: 'Admin',
    messageKicker: 'Vereinsnachricht',
    messageText: 'Jede Begegnung ist eine neue Brücke. Willkommen bei uns.',
    messageTextTwo: 'Unsere Kultur ist der Anfang unserer Zukunft.',
    messageTextThree: 'Nächstes Treffen: Ein Abend mit afghanischer Küche & Gastfreundschaft in Münster',
    calloutEyebrow: 'Wurzeln, die uns begleiten',
    calloutText: 'Von den Bergen Afghanistans bis ins Herz Europas: Unsere Kultur und Gemeinschaft leben voller Hoffnung weiter.',
    joinButton: 'Mitmachen',
    discoverButton: 'Mehr über uns',
    strip1Title: 'Kulturzentrum in Münster',
    strip1Sub: 'Münster, NRW Deutschland',
    strip2Title: 'Gastfreundschaft & Tee',
    strip2Sub: 'Ein herzlicher Ort für alle',
    strip3Title: 'Zusammenhalt & Dialog',
    strip3Sub: 'Verbindung zwischen zwei Welten',
    eyebrow: 'Von Kabul bis Münster, gemeinsam',
    heroTitle: 'Ein Zuhause für Kultur, Dialog & Zukunft',
    heroCopy: 'Neuer Blick Verein e.V. ist ein unabhängiger, gemeinnütziger Verein in Münster: ein Ort zur Bewahrung unserer Kultur, zur Stärkung der Jugend und zum Aufbau neuer Bildungschancen.',
    stat1Desc: 'Jahre Engagement & Gemeinschaft',
    stat2Desc: 'Mitglieder, Ehrenamtliche & Freunde',
    stat3Desc: 'Workshops, Seminare & Kulturfeste',
    floatingStatText: 'Gemeinnützig, unabhängig & aktiv',
    labelAbout: 'Über den Verein',
    aboutTitle: 'Unsere Wurzeln sind<br /><em>unsere Zukunft.</em>',
    aboutText: 'Wir sind ein gemeinnütziger, unabhängiger Verein in Münster. Ein Ort, an dem wir reiche Traditionen pflegen, Neuzugewanderte unterstützen, junge Menschen fördern und Brücken zur deutschen Gesellschaft schlagen.',
    readMore: 'Unsere Geschichte',
    value1Title: 'Identität & Kultur',
    value1Text: 'Bewahrung der Sprachen Dari & Pashto, Dichtung, Kunst und traditioneller Feste wie Nowruz.',
    value2Title: 'Bildung & Chancen',
    value2Text: 'Workshops, Studienberatung, Orientierungshilfe und Deutsch-Sprachförderung für neue Perspektiven.',
    value3Title: 'Zusammenhalt & Frieden',
    value3Text: 'Ein sicherer Raum des Respekts und der Unterstützung für alle Familien, Frauen und Jugendliche.',
    labelActivities: 'Unser Wirken',
    activitiesTitle: 'Was wir<br /><em>gemeinsam schaffen</em>',
    activitiesSub: 'Regelmäßige kulturelle, bildende und soziale Treffen für alle Generationen',
    activity1Title: 'Kultur, Kunst & Tradition',
    activity1Text: 'Poesie- und Erzählabende, Ausstellungen traditioneller Teppiche und Feiern zum afghanischen Neujahr.',
    activity2Title: 'Bildung & Fähigkeiten',
    activity2Text: 'Förderkurse für Schüler, digitale Kompetenzen und deutsch-afghanischer Sprachaustausch.',
    activity3Title: 'Jugend, Frauen & Familie',
    activity3Text: 'Frauen-Empowerment, Jugendforen, gemeinsame Ausflüge und familiäre Teestunden.',
    activity4Title: 'Frieden & Dialog',
    activity4Text: 'Austausch mit zivilgesellschaftlichen Partnern in Münster, Antidiskriminierung und gelebte Vielfalt.',
    labelEvent: 'Nächste Veranstaltung',
    eventDate: 'Samstag, 21. September 2024 · Münster',
    eventTitle: 'Ein Tisch,<br />tausend Geschichten.',
    eventText: 'Ein Fest der Sinne mit traditionellen afghanischen Speisen, grünem Tee, Gedichten und Begegnungen in Münster. Alle sind herzlich willkommen.',
    eventButton: 'Zur Veranstaltung anmelden',
    eventLocationBtn: 'Veranstaltungsort',
    labelGallery: 'Bildergalerie',
    galleryTitle: 'Momente, die<br /><em>bleiben.</em>',
    galleryHint: 'Klicke auf ein Bild, um es in voller Größe zu betrachten.',
    quote: 'Wenn wir zusammenstehen, ist Zuhause kein Ort auf einer Landkarte mehr, sondern ein Gefühl, das wir gemeinsam im Herzen tragen.',
    quoteBy: '— Mitglied des Neuer Blick Vereins in Münster',
    labelTogether: 'Mach mit',
    membershipTitle: 'Dein Platz ist<br /><em>hier.</em>',
    membershipText: 'Werde Mitglied, bring deine Talente ehrenamtlich ein oder komm einfach auf einen grünen Tee mit Kardamom vorbei. Jede Begegnung zählt.',
    membershipButton: 'Mitglied werden',
    labelContact: 'Bleib in Kontakt',
    contactTitle: 'Sag Hallo,<br /><em>wir sind da.</em>',
    contactText: 'Für Partnerschaften, Mitgliedschaft oder Fragen zu unseren Projekten: Wir freuen uns auf deine Nachricht.',
    contactMessageBtn: 'Nachricht senden',
    addressLabel: 'Adresse',
    phoneLabel: 'Telefon',
    emailLabel: 'E-Mail',
    footerText: 'Kultur. Zusammenhalt. Zukunft.',
    footerContact: 'Kontakt',
    footerLegal: 'Impressum',
    footerPrivacy: 'Datenschutz',
    socialLabel: 'Folge uns:',
    formNameLabel: 'Vor- und Nachname *',
    formEmailLabel: 'E-Mail-Adresse *',
    formPhoneLabel: 'Telefonnummer / WhatsApp',
    formInterestLabel: 'Art der Anfrage',
    formNotesLabel: 'Ihre Nachricht (optional)',
    formSubmitBtn: 'Anfrage absenden',
    munsterCity: 'Münster',
    kabulCity: 'Kabul',
    messageTextFour: 'Kostenlose Beratung für Ausbildung, Studium und Berufseinstieg',
    navOpportunities: 'Karriere & Studium',
    labelOpportunities: 'Zukunft & Perspektiven',
    opportunitiesTitle: 'Jobchancen,<br /><em>Studium & Stipendien</em>',
    opportunitiesSub: 'Umfassende Orientierung und Unterstützung des Neuer Blick Vereins für Ausbildung, Universität und Stipendien in Deutschland',
    jobTag: 'Beruf & Karriere',
    jobCardTitle: 'Arbeitsmöglichkeiten & Berufseinstieg',
    jobCardDesc: 'Praktische Wege zu qualifizierten Arbeitsplätzen, Anerkennung ausländischer Abschlüsse und dualer Ausbildung.',
    jobP1Title: 'Anerkennung von Abschlüssen',
    jobP1Desc: 'Schritt-für-Schritt-Begleitung zur Anerkennung beruflicher Qualifikationen in Deutschland.',
    jobP2Title: 'Duale Berufsausbildung',
    jobP2Desc: 'Mehr als 350 anerkannte Ausbildungsberufe mit monatlicher Vergütung und Festanstellungschancen.',
    jobP3Title: 'Professionelle Bewerbungsunterlagen',
    jobP3Desc: 'Erstellung von Lebenslauf und Anschreiben nach deutschen Standards für Arbeitgeber in NRW.',
    jobP4Title: 'Jobvermittlung & Netzwerke',
    jobP4Desc: 'Nutzung offizieller Jobportale und Kontakt zu aufgeschlossenen Unternehmen und Unternehmern.',
    jobActionBtn: 'Kostenlose Berufsberatung',
    studyTag: 'Universität & Förderung',
    studyCardTitle: 'Studium & Stipendien in Deutschland',
    studyCardDesc: 'Leitfaden für Zulassung an deutschen Hochschulen, Bachelor- und Masterprogramme sowie Stipendien.',
    studyP1Title: 'Hochschulzulassung & Uni-Assist',
    studyP1Desc: 'Bewerbung über Uni-Assist, Vorbereitungskurse (Studienkolleg) und Studiengangswahl.',
    studyP2Title: 'Stipendienprogramme (DAAD u.a.)',
    studyP2Desc: 'Förderprogramme des DAAD, politischer Stiftungen sowie BAföG-Möglichkeiten für Studierende.',
    studyP3Title: 'Sprachprüfungen (TestDaF / DSH / C1)',
    studyP3Desc: 'Vorbereitung auf akademische Sprachzertifikate für das Hochschulstudium in Deutschland.',
    studyP4Title: 'Studentisches Mentoring',
    studyP4Desc: 'Direkter Austausch mit afghanischen Studierenden und Alumni an der Universität Münster.',
    studyActionBtn: 'Studienberatung anfragen',
    moreInfo: 'Mehr erfahren',
    frameCaption: 'Gemeinsam stärker',
    tagFood: '🍲 Traditionelle Küche',
    tagTea: '🫖 Tee & Gebäck',
    tagTalk: '🗣 Begegnung',
    tagFree: '🎟 Eintritt frei',
    cdLabel: 'Bis zum Beginn',
    cdDays: 'Tage',
    cdHours: 'Std.',
    cdMinutes: 'Min.',
    cdSeconds: 'Sek.',
    cdSoon: 'Der nächste Termin wird bald bekanntgegeben.',
    addCalendar: 'Zum Kalender',
    shareEvent: 'Teilen',
    benefit1: 'Teilnahme an exklusiven Workshops und Kursen',
    benefit2: 'Vorrang und Rabatte bei Festen und Jahresveranstaltungen',
    benefit3: 'Netzwerk für Studium, Beruf und rechtliche Fragen',
    artTitle: 'Mitglied bei Neuer Blick',
    artText: 'Eine große Familie, die afghanische Kultur und Zukunft in Münster und Deutschland stärkt.',
    labelFaq: 'Häufige Fragen',
    faqTitle: 'Fragen?<br /><em>Hier sind Antworten.</em>',
    faqSub: 'Kurze Antworten auf die häufigsten Fragen zu Mitgliedschaft, Beratung und Programmen.',
    faqAsk: 'Eine andere Frage?',
    faq1Q: 'Wer kann Mitglied werden?',
    faq1A: 'Alle, die sich für afghanische Kultur und gesellschaftlichen Zusammenhalt interessieren, unabhängig von Herkunft, Alter oder Nationalität. Einfach das Mitgliedsformular ausfüllen.',
    faq2Q: 'Ist die Beratung zu Beruf und Studium kostenlos?',
    faq2A: 'Ja. Unsere Begleitung zu Arbeit, Ausbildung, Studium und Stipendien ist ehrenamtlich und kostenlos.',
    faq3Q: 'In welchen Sprachen finden die Angebote statt?',
    faq3A: 'Vor allem auf Dari/Persisch, Paschtu und Deutsch. Bei Bedarf helfen wir auch auf Englisch.',
    faq4Q: 'Wie kann ich mich ehrenamtlich engagieren?',
    faq4A: 'Öffne das Kontaktformular und wähle „Ehrenamtliche Mitarbeit“. Unser Team meldet sich für ein Kennenlernen.',
    faq5Q: 'Wo ist das Vereinsbüro?',
    faq5A: 'Unser Büro ist in der Strinfurter Straße 70, 48149 Münster. Bitte vereinbare vor einem Besuch einen Termin.',
    actCall: 'Anrufen',
    actWhatsapp: 'WhatsApp',
    actEmail: 'E-Mail',
    actRoute: 'Route',
    copied: 'Kopiert!',
    linkCopied: 'Event-Link kopiert.',
    footerArtCaption: 'Von Kabul bis Münster – eine Brücke aus Kultur, Freundschaft und Hoffnung',
    footerAbout: 'Ein unabhängiger, gemeinnütziger Verein in Münster für Kultur, Bildung und Zusammenhalt.',
    footerExplore: 'Entdecken',
    footerPrograms: 'Programme',
    newsletterTitle: 'Newsletter',
    newsletterText: 'Erfahre als Erste von Veranstaltungen und neuen Chancen.',
    newsletterDone: 'Danke! Du bist jetzt für den Newsletter angemeldet.',
    footerMade: 'Mit ♥ gemacht in Münster',
    devLabel: 'Design & Entwicklung:',
    devName: 'Shoaib Obaidi',
    messageKickerTwo: 'Kabul ↔ Münster',
    frameCity: 'Münster, Deutschland',
    floatingStatValue: '100%',
    stampCity: 'MÜNSTER',
    stampYear: '2026',
    artBadge: 'Vereinsmitglied',
    artFooter: 'Münster e.V.',
    footerCopyright: 'Neuer Blick Verein e.V. · Alle Rechte vorbehalten.',
    modalBadge: 'Neuer Blick e.V.',
    loaderText: 'Neuer Blick Verein · Münster',
    scrollHint: 'SCROLL',
    modalMembershipTitle: 'Mitgliedsantrag Neuer Blick',
    modalMembershipSub: 'Werde Teil unserer Gemeinschaft. Wir freuen uns auf dich!',
    modalEventTitle: 'Anmeldung: Ein Tisch, tausend Geschichten',
    modalEventSub: 'Sichere dir deinen Platz für unseren afghanischen Kulturabend.',
    modalJobTitle: 'Berufsberatung & Karriere in Deutschland',
    modalJobSub: 'Sprich mit unseren Arbeits- und Ausbildungsmentoren in Münster.',
    modalStudyTitle: 'Studien- & Stipendienberatung',
    modalStudySub: 'Hilfe bei Uni-Assist, Sprachkursen und DAAD-Stipendien.',
    modalGeneralTitle: 'Kontaktformular',
    modalGeneralSub: 'Schreib uns deine Frage oder Kooperationsidee.',
    thanksMsg: 'Vielen Dank, {name}! Deine Anfrage wurde erfolgreich gesendet.',
    friendWord: 'liebe Freundin, lieber Freund',
    sendError: 'Senden fehlgeschlagen. Bitte versuche es erneut oder schreib uns eine E-Mail.',
    sending: 'Wird gesendet…',
    optMembership: 'Mitgliedsantrag',
    optEvent: 'Anmeldung zur Kulturveranstaltung',
    optJob: 'Berufsberatung & Jobsuche in Deutschland',
    optStudy: 'Studienberatung, Universität & Stipendien',
    optVolunteer: 'Ehrenamtliche Mitarbeit & Unterricht',
    optGeneral: 'Allgemeine Frage oder Kooperation',
    formNamePh: 'z. B. Ahmad Rahimi',
    formNotesPh: 'Schreib deine Nachricht hier…'
  },
  en: {
    brandName: 'New Perspective Association',
    brandSub: 'Neuer Blick Verein e.V.',
    navAbout: 'About us',
    navActivities: 'Activities',
    navEvents: 'Events',
    navStories: 'Our stories',
    navGallery: 'Gallery',
    navMembership: 'Membership',
    navContact: 'Contact',
    loginButton: 'Admin',
    messageKicker: 'Association message',
    messageText: 'Every encounter is a new bridge. Welcome to our community.',
    messageTextTwo: 'Our culture is where our future begins.',
    messageTextThree: 'Next gathering: An evening of Afghan cuisine & hospitality in Münster',
    calloutEyebrow: 'Roots that travel with us',
    calloutText: 'From the towering mountains of Afghanistan to the heart of Europe, our culture and community thrive with hope.',
    joinButton: 'Join us',
    discoverButton: 'Discover more',
    strip1Title: 'Cultural Hub in Münster',
    strip1Sub: 'Münster, NRW Germany',
    strip2Title: 'Hospitality & Tea',
    strip2Sub: 'A warm welcome for everyone',
    strip3Title: 'Solidarity & Bridge Building',
    strip3Sub: 'Connecting two cultures',
    eyebrow: 'From Kabul to Münster, together',
    heroTitle: 'A home for culture, dialogue and future',
    heroCopy: 'Neuer Blick Verein e.V. is an independent non-profit in Münster: a vibrant space to preserve our heritage, empower youth, and foster new social and educational opportunities.',
    stat1Desc: 'Years of community & dedication',
    stat2Desc: 'Members, volunteers & supporters',
    stat3Desc: 'Workshops, seminars & cultural fests',
    floatingStatText: 'Non-profit, independent & active',
    labelAbout: 'About the association',
    aboutTitle: 'Our roots are<br /><em>our future.</em>',
    aboutText: 'We are an independent non-profit association in Münster: a welcoming space preserving heritage, mentoring newcomers, empowering youth, and building lasting bridges with the wider community.',
    readMore: 'Read our story',
    value1Title: 'Identity & Culture',
    value1Text: 'Preserving Dari and Pashto languages, poetry, arts, and joyous ancient celebrations like Nowruz.',
    value2Title: 'Education & Opportunity',
    value2Text: 'Skill-building workshops, academic guidance, administrative counseling, and language exchange.',
    value3Title: 'Solidarity & Peace',
    value3Text: 'A safe, respectful space fostering solidarity and mutual care across all generations.',
    labelActivities: 'What we do',
    activitiesTitle: 'What we<br /><em>build together</em>',
    activitiesSub: 'Regular cultural, educational, and social gatherings for all generations',
    activity1Title: 'Culture, Art & Heritage',
    activity1Text: 'Poetry and storytelling evenings, artisan carpet exhibits, and seasonal cultural celebrations.',
    activity2Title: 'Education & Learning',
    activity2Text: 'School tutoring, digital literacy workshops, and German-Dari conversational tandems.',
    activity3Title: 'Youth, Women & Family',
    activity3Text: 'Women empowerment circles, youth dialogue, outdoor community trips, and family tea gatherings.',
    activity4Title: 'Peace & Cultural Dialogue',
    activity4Text: 'Collaborative exchange with local civic groups, combating prejudice, and sharing authentic cultural stories.',
    labelEvent: 'Upcoming Event',
    eventDate: 'Saturday, 21 September 2024 · Münster',
    eventTitle: 'One Table,<br />A Thousand Stories.',
    eventText: 'A celebration of Afghan culinary traditions, cardamom tea, poetry, and warm conversations in Münster.',
    eventButton: 'Register for event',
    eventLocationBtn: 'Event location',
    labelGallery: 'Photo Gallery',
    galleryTitle: 'Moments that<br /><em>stay.</em>',
    galleryHint: 'Click any image to view in full resolution.',
    quote: 'When we stand together, home is no longer just a place on a map; it is a feeling we build together with warmth and solidarity.',
    quoteBy: '— A member of Neuer Blick Association in Münster',
    labelTogether: 'Join our journey',
    membershipTitle: 'Your place is<br /><em>here.</em>',
    membershipText: 'Become a member, share your talents as a volunteer, or simply join us for a cup of cardamom green tea. Every encounter brings warmth.',
    membershipButton: 'Become a member',
    labelContact: 'Get in touch',
    contactTitle: 'Say hello,<br /><em>we are here.</em>',
    contactText: 'For partnerships, membership inquiries, volunteering, or questions: we would love to hear from you.',
    contactMessageBtn: 'Send message',
    addressLabel: 'Address',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    footerText: 'Culture. Solidarity. Future.',
    footerContact: 'Contact',
    footerLegal: 'Legal Notice',
    footerPrivacy: 'Privacy Policy',
    socialLabel: 'Follow us:',
    formNameLabel: 'Full Name *',
    formEmailLabel: 'Email Address *',
    formPhoneLabel: 'Phone / WhatsApp',
    formInterestLabel: 'Request Type',
    formNotesLabel: 'Your message (optional)',
    formSubmitBtn: 'Submit request',
    munsterCity: 'Münster',
    kabulCity: 'Kabul',
    messageTextFour: 'Free mentoring for job search, apprenticeships, and study in Germany',
    navOpportunities: 'Jobs & Study in Germany',
    labelOpportunities: 'Future & Careers in Germany',
    opportunitiesTitle: 'Job Opportunities,<br /><em>Study & Scholarships</em>',
    opportunitiesSub: 'Comprehensive guidance and community support for entering the German job market, universities, and scholarship programs',
    jobTag: 'Career & Jobs',
    jobCardTitle: 'Job Opportunities in Germany',
    jobCardDesc: 'Practical pathways to formal employment, foreign credential recognition, and dual vocational training.',
    jobP1Title: 'Degree & Credential Recognition (Anerkennung)',
    jobP1Desc: 'Step-by-step mentoring for getting engineering, healthcare, and technical qualifications recognized.',
    jobP2Title: 'Dual Vocational Training (Ausbildung)',
    jobP2Desc: 'Over 350 recognized professions combining hands-on workplace training with a monthly salary.',
    jobP3Title: 'Professional Resume & Cover Letter (Bewerbung)',
    jobP3Desc: 'Tailoring standard German resumes (Lebenslauf) and motivation letters for employers in Münster and NRW.',
    jobP4Title: 'Job Search & Professional Networking',
    jobP4Desc: 'Access to official job portals (Jobcenter, StepStone) and connections with supportive local employers.',
    jobActionBtn: 'Free Career Consultation',
    studyTag: 'University & Scholarships',
    studyCardTitle: 'Study in Germany & Scholarships',
    studyCardDesc: 'Guidance on German university admission, tuition-free Bachelor and Master programs, and funding.',
    studyP1Title: 'University Admission & Uni-Assist',
    studyP1Desc: 'Applying through Uni-Assist, completing Studienkolleg preparation, and selecting future-proof degrees.',
    studyP2Title: 'Scholarship Programs (DAAD & Foundations)',
    studyP2Desc: 'Overview of DAAD grants, political foundation scholarships, and state financial support (BAföG).',
    studyP3Title: 'Language Certificates (TestDaF & DSH)',
    studyP3Desc: 'Preparation resources and workshops for achieving B2/C1 certification required for university entrance.',
    studyP4Title: 'Student Mentoring & Peer Support',
    studyP4Desc: 'Direct mentoring with Afghan students and alumni currently studying at Münster University (WWU).',
    studyActionBtn: 'Request Study & Scholarship Mentoring',
    moreInfo: 'Learn more',
    frameCaption: 'Stronger together',
    tagFood: '🍲 Traditional food',
    tagTea: '🫖 Tea & sweets',
    tagTalk: '🗣 Conversation',
    tagFree: '🎟 Free entry',
    cdLabel: 'Until the event begins',
    cdDays: 'Days',
    cdHours: 'Hours',
    cdMinutes: 'Min',
    cdSeconds: 'Sec',
    cdSoon: 'The next date will be announced soon.',
    addCalendar: 'Add to calendar',
    shareEvent: 'Share',
    benefit1: 'Access to exclusive workshops and classes',
    benefit2: 'Priority and discounts for festivals and annual events',
    benefit3: 'A support network for study, work and legal questions',
    artTitle: 'Neuer Blick Membership',
    artText: 'One big family supporting Afghan culture and its future in Münster and Germany.',
    labelFaq: 'Frequently asked',
    faqTitle: 'Questions?<br /><em>Here are answers.</em>',
    faqSub: 'Short answers to the most common questions about membership, mentoring and our programs.',
    faqAsk: 'Have another question?',
    faq1Q: 'Who can become a member?',
    faq1A: 'Everyone who cares about Afghan culture and community, whatever their background, age or nationality. Just fill in the membership form.',
    faq2Q: 'Is the job and study mentoring free?',
    faq2A: 'Yes. Our guidance on work, Ausbildung, university and scholarships is volunteer-run and free of charge.',
    faq3Q: 'Which languages are the programs in?',
    faq3A: 'Mostly Dari/Persian, Pashto and German, and we are happy to help in English too.',
    faq4Q: 'How can I volunteer?',
    faq4A: 'Open the contact form and choose “Volunteering”. Our team will get in touch to meet you.',
    faq5Q: 'Where is the office?',
    faq5A: 'Our office is at Strinfurter Straße 70, 48149 Münster. Please arrange a time before visiting.',
    actCall: 'Call',
    actWhatsapp: 'WhatsApp',
    actEmail: 'Email',
    actRoute: 'Directions',
    copied: 'Copied!',
    linkCopied: 'Event link copied.',
    footerArtCaption: 'From Kabul to Münster: a bridge of culture, friendship and hope',
    footerAbout: 'An independent non-profit in Münster for culture, education and community.',
    footerExplore: 'Explore',
    footerPrograms: 'Programs',
    newsletterTitle: 'Newsletter',
    newsletterText: 'Be the first to hear about events and new opportunities.',
    newsletterDone: 'Thank you! You are subscribed to the newsletter.',
    footerMade: 'Made with ♥ in Münster',
    devLabel: 'Designed & developed by',
    devName: 'Shoaib Obaidi',
    messageKickerTwo: 'Kabul ↔ Münster',
    frameCity: 'Münster, Germany',
    floatingStatValue: '100%',
    stampCity: 'MÜNSTER',
    stampYear: '2026',
    artBadge: 'Member',
    artFooter: 'Münster e.V.',
    footerCopyright: 'Neuer Blick Verein e.V. · All rights reserved.',
    modalBadge: 'Neuer Blick e.V.',
    loaderText: 'Neuer Blick Verein · Münster',
    scrollHint: 'SCROLL',
    modalMembershipTitle: 'Membership Application',
    modalMembershipSub: 'Become part of our family in Münster.',
    modalEventTitle: 'Event RSVP: One Table, A Thousand Stories',
    modalEventSub: 'Reserve your seat for an evening of Afghan cuisine and good company.',
    modalJobTitle: 'Job & Career Consultation in Germany',
    modalJobSub: 'Get guidance on credential recognition, Ausbildung, and job search.',
    modalStudyTitle: 'University Study & Scholarship Mentoring',
    modalStudySub: 'Support for Uni-Assist applications, language tests, and scholarships.',
    modalGeneralTitle: 'Quick Contact',
    modalGeneralSub: 'Send us your questions or partnership proposals.',
    thanksMsg: 'Thank you, {name}! Your request has been sent.',
    friendWord: 'friend',
    sendError: 'Sending failed. Please try again or email us.',
    sending: 'Sending…',
    optMembership: 'Membership application',
    optEvent: 'Cultural event registration',
    optJob: 'Job & career consultation in Germany',
    optStudy: 'Study, university & scholarship guidance',
    optVolunteer: 'Volunteering & teaching',
    optGeneral: 'General question or partnership',
    formNamePh: 'e.g. Ahmad Rahimi',
    formNotesPh: 'Write your message here…'
  }
};

const defaultGalleryItems = [
  {
    url: 'images/hero-background.jpg',
    title: 'طبیعت بکر و دریاچه‌های بند امیر در ولایت بامیان افغانستان',
    titleDe: 'Band-e Amir Nationalpark & Berge in Bamiyan, Afghanistan',
    titleEn: 'Band-e Amir National Park & Mountains in Bamiyan, Afghanistan',
    titlePs: 'د افغانستان د بامیان ولایت د بند امیر طبیعت او جهیلونه'
  },
  {
    url: 'images/activity-family.jpg',
    title: 'سنت مهمان‌نوازی افغان و نوشیدن چای با زعفران و هل',
    titleDe: 'Traditionelle Tee-Zeremonie mit Safran & Kardamom',
    titleEn: 'Traditional Afghan Tea Ceremony with Saffron & Cardamom',
    titlePs: 'د افغان مېلمه‌پالنې دود او د زعفرانو او هېلو چای'
  },
  {
    url: 'images/activity-culture.jpg',
    title: 'هنر دست‌باف قالی و گلیم اصیل افغان با نقوش سنتی',
    titleDe: 'Handgewebte traditionelle afghanische Teppichkunst',
    titleEn: 'Handwoven Traditional Afghan Carpets & Kilims',
    titlePs: 'د افغان لاسي اوبدل شویو قالینو او ګلیمو هنر'
  },
  {
    url: 'images/event-dinner.jpg',
    title: 'ضیافت شام فرهنگی "یک میز، هزار داستان" با غذاهای سنتی',
    titleDe: 'Kulturelles Festessen mit traditioneller Küche in Münster',
    titleEn: 'Community Cultural Feast & Afghan Cuisine in Münster',
    titlePs: 'د «یو دسترخوان، زر کیسې» کلتوري ماښامنۍ له دودیزو خوړو سره'
  },
  {
    url: 'images/activity-education.jpg',
    title: 'کارگاه‌های آموزشی، کتاب‌خوانی و توانمندسازی جوانان',
    titleDe: 'Bildungs-Workshops, Tandems & Jugendförderung',
    titleEn: 'Educational Workshops & Youth Empowerment',
    titlePs: 'ښوونیز ورکشاپونه، کتاب لوستل او د ځوانانو پیاوړتیا'
  },
  {
    url: 'images/activity-dialogue.jpg',
    title: 'پیوند همبستگی، مهربانی و امید در میان خانواده‌ها و جامعه',
    titleDe: 'Zusammenhalt, Vielfalt & gegenseitige Unterstützung',
    titleEn: 'Solidarity, Inclusion & Mutual Community Support',
    titlePs: 'د کورنیو او ټولنې ترمنځ یووالی، مهرباني او هیله'
  }
];

const DEFAULT_EVENT = {
  date: '2026-11-21T18:00',
  durationHours: 4,
  location: ''
};

const DEFAULT_STATS = { years: 10, members: 500, events: 45 };

const DEFAULT_CONTACT = {
  addressStreet: 'Strinfurter Straße 70',
  addressCity: '48149 Münster',
  addressCountry: 'Deutschland',
  phone: '+49 251 987 654 30',
  whatsapp: '',
  email: 'hallo@neuerblick-verein.de'
};

const DEFAULT_SOCIAL = {
  instagram: 'https://instagram.com',
  facebook: 'https://facebook.com',
  youtube: 'https://youtube.com',
  tiktok: 'https://tiktok.com'
};

// Every photo on the website. Admin uploads replace these paths with files saved in images/.
const DEFAULT_IMAGES = {
  calloutBg: 'images/hero-background.jpg',
  heroMain: 'images/community-munster.jpg',
  activity1: 'images/activity-culture.jpg',
  activity2: 'images/activity-education.jpg',
  activity3: 'images/activity-family.jpg',
  activity4: 'images/activity-dialogue.jpg',
  eventImage: 'images/event-dinner.jpg',
  footerArt: 'images/kabul-muenster-bridge.jpg'
};
